export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_ITEM = 'UPDATE_ITEM';
